### ISSUE TITLE
Component Tab 没有数据，History Tab 数据正常

### ISSUE THREAD

**Issue by lb091188** [ecomfe/san-devtool#4]
#### Component Tab
![image](https://user-images.githubusercontent.com/16659166/60781748-2aee8b80-a176-11e9-9703-a43a942d6f2d.png)
#### History Tab
![image](https://user-images.githubusercontent.com/16659166/60781771-4194e280-a176-11e9-8cd5-18df908396a0.png)

**Comment by lb091188** [comment]
**此时，从控制台读取开发工具的数据时能够看到组件树的数据的，但是却不能够显示在开发者工具上面**
![image](https://user-images.githubusercontent.com/16659166/60782117-e5cb5900-a177-11e9-9d88-51c960dec5ff.png)

**Comment by luyuan** [comment]
san-devtool 更新到了 1.1.3，并通过 San 3.7.7 验证。现在可以通过

- Chrome Web Store: https://chrome.google.com/webstore/detail/san-devtool/pjnngoafflflkagpebgfifjejlnfhahc
- Github: https://github.com/baidu/san-devtool/releases/tag/1.1.3
- NPM: https://www.npmjs.com/package/san-devtool

这三个渠道下载到最新版 san-devtool。

**Comment by lb091188** [comment]
查看到已经修复，非常感谢
